name: pmsbweb
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  markdown: ^2.0.3
  html: ^0.14.0+2
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  uuid: 2.0.1
  firebase: ^5.0.0
  queries: ^0.1.12
  firestore_wrapper_web:
        git:
            url: https://github.com/paulorobertocruz/firestore_wrapper.git
            path: packages/firestore_wrapper_web
  
dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
